# Site settings
title: Fluo
baseurl: "" # the subpath of site
url: "http://fluo.io" # the base hostname & protocol for your site

permalink: :title
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Number of posts displayed on the home page.
num_home_posts: 5

# Color scheme based on http://flatuicolors.com/.
color: default

# Fluo specific settings
latest_release: "1.0.0-beta-2"
